name: ChestCleaner
version: 1.6.4
author: Tom2208
api-version: 1.13

main: chestcleaner.main.Main

commands:
  cleaninventory:
    description: Cleans an inventory of a block.
    usage: /<command> <x> <y> <z>
  timer:
    description: Configuers the timer.
    usage: /<command> <setActive/setTime>
  cleaningitem:
    description: Configuration of the cleaningitem.
    usage: /<command> <setActive/setItem/setdurability/give/get/rename>
  blacklist:
    description: Avoiding items to get stacked while sorting.
    usage: /<command> <sorting/inventories> <list/clear/addMaterial/removeMaterial>