name: ChestCleaner
version: 1.7
author: Tom2208
api-version: 1.13

main: chestcleaner.main.Main

commands:
  cleaninventory:
    description: Cleans an inventory of a block.
    usage: /<command> <x> <y> <z>
  timer:
    description: Configures the timer.
    usage: /<command> <setActive/setTime>
  cleaningitem:
    description: Configuration of the cleaningitem.
    usage: /<command> <get/give/rename/setActive/setDurabilityLoss/setEventDetectionMode/setItem/setLore>
  blacklist:
    description: Avoiding items to get stacked while sorting.
    usage: /<command> <sorting/inventories> <list/clear/addMaterial/removeMaterial>
  sortingconfig:
    description: Configuration of the sorting algorithm.
    usage: /<command> <pattern/evaluator/setautosort/adminconfig>
