name: ChestCleanerX
version: "0.1"
author: Tom2208, graves501
api-version: "1.15"

main: io.github.graves501.chestcleanerx.main.ChestCleanerX

commands:
  cleanInventory:
    description: Cleans an inventory of a block.
    usage: /<command> <x> <y> <z>
  timer:
    description: Configures the timer.
    usage: /<command> <setActive/setTime>
  cleaningItem:
    description: Configuration of the cleaningItem.
    usage: /<command> <get/give/rename/setActive/setDurabilityLoss/setEventDetectionMode/setItem/setLore>
  blacklist:
    description: Avoiding items to get stacked while sorting.
    usage: /<command> <sorting/inventories> <list/clear/addMaterial/removeMaterial>
  sortingConfig:
    description: Configuration of the sorting algorithm.
    usage: /<command> <pattern/evaluator/setAutosort/adminConfig>

permissions:
  chestCleanerX.cleaningItem.use:
    default: true
  chestCleanerX.cleaningItem.sortOwnInventory:
    default: true
  chestCleanerX.autoRefill.blocks:
    default: true
  chestCleanerX.autoRefill.consumables:
    default: true
